/* (Beta) Export of data model SimulationScenario of the subject dataModel.WaterDistributionManagementEPANET for a PostgreSQL database. Pending translation of enumerations and multityped attributes */
CREATE TYPE SimulationScenario_demandModel_type AS ENUM ('DDA', 'PDA');
CREATE TYPE SimulationScenario_flowUnits_type AS ENUM ('AFD', 'CFS', 'CMD', 'CMH', 'GPM', 'IMGD', 'LPS', 'LPM', 'MLD', 'MGD');
CREATE TYPE SimulationScenario_headlossFormula_type AS ENUM ('H-W', 'D-W', 'C-M');
CREATE TYPE SimulationScenario_initialStatus_type AS ENUM ('OPEN', 'CLOSED', 'CV');
CREATE TYPE SimulationScenario_qualityType_type AS ENUM ('age', 'chem', 'none', 'trace');
CREATE TYPE SimulationScenario_statistic_type AS ENUM ('averaged', 'maximum', 'minimum', 'none', 'range');
CREATE TYPE SimulationScenario_status_type AS ENUM ('OPEN', 'CLOSED', 'CV');
CREATE TYPE SimulationScenario_type AS ENUM ('SimulationScenario');
CREATE TYPE SimulationScenario_unbalanced_type AS ENUM ('stop', 'continue', 'continue_N');
CREATE TYPE SimulationScenario_valveType_type AS ENUM ('FCV', 'GPV', 'PBV', 'PRV', 'PSV', 'TCV');
CREATE TABLE SimulationScenario (
  "accuracy" NUMERIC,
  "address" JSON,
  "alternateName" TEXT,
  "areaServed" TEXT,
  "bulkOrder" NUMERIC,
  "checkFrequency" NUMERIC,
  "chemicalName" TEXT,
  "chemicalUnits" TEXT,
  "concentrationLimit" NUMERIC,
  "createdBy" JSON,
  "dampLimit" NUMERIC,
  "dataProvider" TEXT,
  "dateCreated" TIMESTAMP,
  "dateModified" TIMESTAMP,
  "demandCategory" JSON,
  "demandCharge" NUMERIC,
  "demandModel" SimulationScenario_demandModel_type,
  "description" TEXT,
  "diffusivity" NUMERIC,
  "duration" NUMERIC,
  "emitterExponent" NUMERIC,
  "energyUse" JSON,
  "flow" JSON,
  "flowChange" NUMERIC,
  "flowUnits" SimulationScenario_flowUnits_type,
  "hasInputNetwork" JSON,
  "hasSimulationResult" JSON,
  "head" JSON,
  "headError" NUMERIC,
  "headlossFormula" SimulationScenario_headlossFormula_type,
  "hydraulicTimeStep" NUMERIC,
  "id" TEXT PRIMARY KEY,
  "initialQuality" JSON,
  "initialStatus" SimulationScenario_initialStatus_type,
  "inputParameter" JSON,
  "level" JSON,
  "location" JSON,
  "maxCheck" NUMERIC,
  "minimumPressure" NUMERIC,
  "name" TEXT,
  "operationalControl" JSON,
  "owner" JSON,
  "patternStart" TIMESTAMP,
  "patternStep" NUMERIC,
  "pressure" JSON,
  "pressureExponent" NUMERIC,
  "quality" JSON,
  "qualityTimeStep" NUMERIC,
  "qualityType" SimulationScenario_qualityType_type,
  "reportStart" NUMERIC,
  "reportStep" NUMERIC,
  "requiredPressure" NUMERIC,
  "ruleTimeStep" NUMERIC,
  "seeAlso" JSON,
  "source" TEXT,
  "sourceCategory" JSON,
  "sourceMassInflow" JSON,
  "specificGravity" NUMERIC,
  "startClockTime" NUMERIC,
  "statistic" SimulationScenario_statistic_type,
  "status" SimulationScenario_status_type,
  "supply" JSON,
  "tag" TEXT,
  "tankOrder" NUMERIC,
  "tolerance" NUMERIC,
  "traceNodeID" JSON,
  "trials" NUMERIC,
  "type" SimulationScenario_type,
  "unbalanced" SimulationScenario_unbalanced_type,
  "unbalancedN" NUMERIC,
  "valveCurve" JSON,
  "valveType" SimulationScenario_valveType_type,
  "velocity" JSON,
  "viscosity" NUMERIC,
  "wallOrder" NUMERIC
);